name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Hello world test
      id: hello-world-test
      uses: education/autograding-command-grader@v1
      with:
        test-name: Hello world test
        setup-command: ''
        command: "./test/helloworld.sh"
        timeout: 10
        max-score: 10
    - name: FizzBuzz test
      id: fizzbuzz-test
      uses: education/autograding-io-grader@v1
      with:
        test-name: FizzBuzz test
        setup-command: ''
        command: "./test/fizzbuzz.sh 15"
        input: ''
        expected-output: Fizz Buzz
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        HELLO-WORLD-TEST_RESULTS: "${{steps.hello-world-test.outputs.result}}"
        FIZZBUZZ-TEST_RESULTS: "${{steps.fizzbuzz-test.outputs.result}}"
      with:
        runners: hello-world-test,fizzbuzz-test
